### ISSUE TITLE
Angezeigte Fragen

### ISSUE THREAD

**Issue by Trikolix** [Trikolix/Fragen-und-Antworten#6]
Auf der Index.php sollen nur noch die Fragen angezeigt werden, welche man noch nicht beantwortet hat.

Wenn man bereits alle Fragen beantwortet hat, soll entsprechende Meldung erscheinen.

Es wäre zu überlegen, ob man Fragen, welche man selbst erstellt hat, auch nicht anzeigen sollte.

**Comment by CamTheOne** [comment]
also die ersten beiden Punkte sind umgesetzte, Fragen die selbst erstellt wurden werden allerdings noch angezeigt ... kann man ja aber immernoch abändern ;)
